set(_CATKIN_CURRENT_PACKAGE "m2wr_gazebo")
set(m2wr_gazebo_VERSION "0.0.0")
set(m2wr_gazebo_MAINTAINER "raptor <raptor@todo.todo>")
set(m2wr_gazebo_PACKAGE_FORMAT "2")
set(m2wr_gazebo_BUILD_DEPENDS )
set(m2wr_gazebo_BUILD_EXPORT_DEPENDS )
set(m2wr_gazebo_BUILDTOOL_DEPENDS "catkin")
set(m2wr_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(m2wr_gazebo_EXEC_DEPENDS )
set(m2wr_gazebo_RUN_DEPENDS )
set(m2wr_gazebo_TEST_DEPENDS )
set(m2wr_gazebo_DOC_DEPENDS )
set(m2wr_gazebo_URL_WEBSITE "")
set(m2wr_gazebo_URL_BUGTRACKER "")
set(m2wr_gazebo_URL_REPOSITORY "")
set(m2wr_gazebo_DEPRECATED "")