# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/choi/catkin_nav/src/yocs_msgs/msg/ARPair.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/ARPairList.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/Wall.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/WallList.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/Column.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/ColumnList.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/MagicButton.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/NavigationControl.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/NavigationControlStatus.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/Table.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/TableList.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/Trajectory.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/TrajectoryList.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/Waypoint.msg;/home/choi/catkin_nav/src/yocs_msgs/msg/WaypointList.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/NavigateToAction.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/NavigateToActionGoal.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/NavigateToActionResult.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/NavigateToActionFeedback.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/NavigateToGoal.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/NavigateToResult.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/NavigateToFeedback.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/DockingInteractorAction.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/DockingInteractorActionGoal.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/DockingInteractorActionResult.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/DockingInteractorActionFeedback.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/DockingInteractorGoal.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/DockingInteractorResult.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/DockingInteractorFeedback.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/LocalizeAction.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/LocalizeActionGoal.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/LocalizeActionResult.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/LocalizeActionFeedback.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/LocalizeGoal.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/LocalizeResult.msg;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg/LocalizeFeedback.msg"
services_str = "/home/choi/catkin_nav/src/yocs_msgs/srv/WaypointListService.srv"
pkg_name = "yocs_msgs"
dependencies_str = "actionlib_msgs;std_msgs;geometry_msgs;std_srvs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "yocs_msgs;/home/choi/catkin_nav/src/yocs_msgs/msg;yocs_msgs;/home/choi/catkin_nav/devel_isolated/yocs_msgs/share/yocs_msgs/msg;actionlib_msgs;/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg;std_msgs;/opt/ros/kinetic/share/std_msgs/cmake/../msg;geometry_msgs;/opt/ros/kinetic/share/geometry_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python2"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
